[package]
name = "dom-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
dom = { path = "../../dom" }
wasm-bindgen = "0.2.92"
web-sys = { version = "0.3.69", features = ["console"] }
